### ISSUE TITLE
Windows: Python 3 + git-bash Unicode error

### ISSUE THREAD

**Issue by hpreston** [kecorbin/virlutils#18]
On Windows in a git-bash terminal commands like `virl ls` and `virl nodes` that display data in tables will result in a `UnicodeEncodeError` if running in Python3 (3.6.2 tested).  See below.  

```bash
(venv)
hapresto@HAPRESTO-TCCVH MINGW64 ~/code/virlutils (master)
$ virl ls
Running Simulations
Traceback (most recent call last):
  File "C:\Users\hapresto\code\virlutils\venv\Scripts\virl-script.py", line 11, in <module>
    load_entry_point('virlutils==0.4', 'console_scripts', 'virl')()
  File "C:\Users\hapresto\code\virlutils\venv\lib\site-packages\click-6.7-py3.6.egg\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\hapresto\code\virlutils\venv\lib\site-packages\click-6.7-py3.6.egg\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\hapresto\code\virlutils\venv\lib\site-packages\click-6.7-py3.6.egg\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\hapresto\code\virlutils\venv\lib\site-packages\click-6.7-py3.6.egg\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\hapresto\code\virlutils\venv\lib\site-packages\click-6.7-py3.6.egg\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\hapresto\code\virlutils\venv\lib\site-packages\virlutils-0.4-py3.6.egg\virl\cli\ls\commands.py", line 26, in ls
  File "C:\Users\hapresto\code\virlutils\venv\lib\site-packages\virlutils-0.4-py3.6.egg\virl\cli\views\sims\sim_views.py", line 22, in sim_list_table
  File "C:\Users\hapresto\code\virlutils\venv\lib\site-packages\click-6.7-py3.6.egg\click\utils.py", line 259, in echo
    file.write(message)
  File "C:\Users\hapresto\code\virlutils\venv\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-79: character maps to <undefined>
(venv)
hapresto@HAPRESTO-TCCVH MINGW64 ~/code/virlutils (master)
$ python -V
Python 3.6.2
(venv)
hapresto@HAPRESTO-TCCVH MINGW64 ~/code/virlutils (master)
$ pip freeze
certifi==2018.1.18
chardet==3.0.4
click==6.7
docopt==0.6.2
idna==2.6
jinja2==2.10
lxml==4.2.1
markupsafe==1.0
python-dateutil==2.7.1
pyyaml==3.12
requests==2.18.4
six==1.11.0
tabulate==0.8.2
urllib3==1.22
virlutils==0.4
```

This problem seems to be isolated to just the git-bash terminal itself as it works find in a native windows cmd prompt.  It also works using git-bash if started with a terminal management program like ConEmu.  

The problem  seems to be the same as noted in this StackOverflow post: https://stackoverflow.com/questions/45660817/python-print-unicode-string-via-git-bash-gets-unicodeencodeerror 

Workarounds include: 

* Use native cmd terminal 
* Use Consol Emulator
* Use Python 2.7

Seems to be an issue not with virlutils but within Click or some other library.  

http://click.pocoo.org/5/python3/

**Comment by hpreston** [comment]
One more note.. action based commands work fine.  You can still `virl up`, `virl down` and `virl ssh` from git-bash with Python 3 in git-bash...
