### ISSUE TITLE
"virl generate" while simulation starting causes error

### ISSUE THREAD

**Issue by hpreston** [kecorbin/virlutils#30]
If you issue a `virl generate` while the simulation is still starting an error is raised that isn't helpful.  

```Traceback (most recent call last):
  File "/Users/hapresto/coding/netdevops_demos/ansible_02/v2_4/bin/virl", line 11, in <module>
    load_entry_point('virlutils==0.5', 'console_scripts', 'virl')()
  File "/Users/hapresto/coding/netdevops_demos/ansible_02/v2_4/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hapresto/coding/netdevops_demos/ansible_02/v2_4/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/hapresto/coding/netdevops_demos/ansible_02/v2_4/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hapresto/coding/netdevops_demos/ansible_02/v2_4/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hapresto/coding/netdevops_demos/ansible_02/v2_4/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hapresto/coding/netdevops_demos/ansible_02/v2_4/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/hapresto/coding/netdevops_demos/ansible_02/v2_4/lib/python3.6/site-packages/virl/cli/generate/ansible/commands.py", line 48, in ansible
    interfaces=interfaces)
  File "/Users/hapresto/coding/netdevops_demos/ansible_02/v2_4/lib/python3.6/site-packages/virl/generators/ansible_inventory.py", line 177, in ansible_inventory_generator
    inventory_yaml = render_yaml_inventory(virl_data, roster, interfaces)
  File "/Users/hapresto/coding/netdevops_demos/ansible_02/v2_4/lib/python3.6/site-packages/virl/generators/ansible_inventory.py", line 146, in render_yaml_inventory
    inventory=generate_inventory_dict(virl_xml, roster=roster, interfaces=interfaces)
  File "/Users/hapresto/coding/netdevops_demos/ansible_02/v2_4/lib/python3.6/site-packages/virl/generators/ansible_inventory.py", line 111, in generate_inventory_dict
    group_map = create_group_map(virl_xml)
  File "/Users/hapresto/coding/netdevops_demos/ansible_02/v2_4/lib/python3.6/site-packages/virl/generators/ansible_inventory.py", line 36, in create_group_map
    root = etree.fromstring(virl_xmlstr)
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1126, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 600, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 710, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 639, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```

**Comment by kecorbin** [comment]
@hpreston i wasn't able to repro this, but have opted for a machete vs a scalpel
